name: Data Schema Code Convention Check

on:
  push:
    paths:
      - '**.sql'

jobs:
  sql-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run SQLFluff linter
        uses: sqlfluff/sqlfluff-github-action@v2.2.0
        with:
          args: "lint --format github ."
